### ISSUE TITLE
A complete guide to install is missing

### ISSUE THREAD

**Issue by csuka** [shuque/danetls#1]
Running Ubuntu 18.04. Installed the dependencies as you state without errors.

Upon compiling your program I receive:

``` 
 ➜  danetls git:(master) ✗ make
cc -g -Wall -Wextra -I. -I/usr/local/openssl/include -I/usr/local/include   -c -o query-getdns.o query-getdns.c
query-getdns.c:27:14: fatal error: event.h: No such file or directory
     #include <event.h>
              ^~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'query-getdns.o' failed
make: *** [query-getdns.o] Error 1
```

**Comment by shuque** [comment]
Ah, yes, sorry. I will add more detailed installation instructions listing pre-requisite packages. Specifically in your case, you'll need to install the "libevent" library and header files.
